# Server Settings
server.bind = 0.0.0.0
server.port = 65432
server.admin.bind = 0.0.0.0
server.admin.port = 65433

# Database Settings (PostgreSQL)
database.type = postgresql
database.host = postgres
database.port = 5432
database.user = ${POSTGRES_USER}
database.password = ${POSTGRES_PASSWORD}
database.database = ${POSTGRES_DB}
database.maximumPoolSize = 32

# Secret Encryption Key
digdag.secret-encryption-key = ${DIGDAG_SECRET_ENCRYPTION_KEY}

# Log Settings
log-server.type = local
log-server.path = /digdag/logs

# Executor Settings
executor.enabled = true
executor.type = local
executor.task-ttl = 1h

# Archive Settings
archive.type = db
